
fpsFromLocalFile["720p/6001-succie"] = 32;

loadedFromLocalFile["720p/6001-succie"] = {
    name: "Succie",
    base: "720p/6001-succie",
    suffix: "_00001_.mp4",
    clothes: 4,
    poses: 4,
    take_good: [{name: "good", variants: 2}],
    take_bad: [{name: "bad", variants: 2}],
    win: [{name: "win", variants: 2}],
    lose: [{name: "lose", variants: 2}],
    bluff_cards: [{name: "cards_bluff", variants: 2, switch_pose: [1]}],
    cheat_cards: [{name: "cards_cheat", variants: 2, switch_pose: [1]}],
    bye_cards: [{name: "cards_bye", variants: 2, switch_pose: [1]}],
    peek_cards: [{name: "cards_peek", variants: 1, switch_pose: [1]}],
    bluff_nocards: [{name: "hand_bluff", variants: 2, switch_pose: [1]}],
    cheat_nocards: [{name: "hand_cheat", variants: 2, switch_pose: [1]}],
    bye_nocards: [{name: "hand_bye", variants: 2, switch_pose: [1]}],
    peek_nocards: [{name: "hand_peek", variants: 1, switch_pose: [1]}],
    show_cards: [{name: "showbreast", variants: 2, switch_pose: [1]},
                 {name: "showfinger1", variants: 2, switch_pose: [1]},
                 {name: "showbreastorgasm", variants: 2, switch_pose: [1]},
                 {name: "showfinger2", variants: 2, switch_pose: [1]},
                ],
    show_nocards: [{name: "showhand1", variants: 2, switch_pose: [1]}],
    pose_cards: [{name: "showshort", variants: 1, switch_pose: [1, 2, 3]}],
    pose_nocards: [{name: "pose_nocards", variants: 1, switch_pose: [1, 2, 3]}],
    intro: [{name: "intro", variants: 1}],
    dress: [{name: "on", variants: 1, switch_clothes: [1]}],
    dress_music: [{file: "audio/ambient/t 07 Let Me Speak of Reason.mp3"}],
    strip: [{name: "off", variants: 1, switch_clothes: [-1]}],
    strip_music: [{file: "audio/ambient/w 05 White and Frozen World.mp3"}],
    finalwin: [{name: "finalwin", variants: 1}],
    finalwin_music: [{file: "audio/ambient/t 10 Eternal Sleep.mp3"}],
    finallose: [{name: "finallose", variants: 1}],
    finallose_music: [{file: "audio/ambient/w 10 Auf Gruenen Wiesen.mp3"}],

    startVolume: 1,
    dimmedVolume: 0.5,
    endVolume: 1,
    dimStep: 0.002,
    tracks: ['audio/ambient/a 07 Isle of Avalon.mp3',
             'audio/ambient/a 01 Aufstieg der Daemonen cut.mp3',
             'audio/ambient/a 02 Glaubst du an Daemonen.mp3',
             'audio/ambient/a 03 The Axe.mp3',
             'audio/ambient/a 04 Burzum.mp3',
             'audio/ambient/a 05 Gebrannte Kinder fuerchten das Feuer.mp3',
             'audio/ambient/a 06 Autumn Night.mp3',
            ]
}